name: Build Nginx Docker Image

on:
  workflow_dispatch:

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Nginx Docker image Amd64
        run: docker build --file centos/centos7/nginx/Dockerfile --tag ghcr.io/${{ github.actor }}/nginx:1.22 . 
    
      - name: Push the Nginx Docker image Amd64
        run: docker push ghcr.io/${{ github.actor }}/nginx:1.22
