name: Docker Mysql 8.4 Rocky Amd64

on:
  workflow_dispatch:

jobs:
  build-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Mysql Docker image
        run: docker build . --file rocky/9/mysql/8.4/Dockerfile --tag ghcr.io/${{ github.actor }}/mysql:8.4-rocky && docker push ghcr.io/${{ github.actor }}/mysql:8.4-rocky
