name: Build Etcd Docker Image

on:
  workflow_dispatch:

jobs:
  build-etcd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Etcd Docker image
        run: docker build . --file centos/centos7/etcd/3.5/Dockerfile --tag ghcr.io/${{ github.actor }}/etcd:3.5 && docker push ghcr.io/${{ github.actor }}/etcd:3.5
