name: Build Redis Docker Image

on:
  workflow_dispatch:

jobs:
  build-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Redis Docker image
        run: docker build . --file centos/centos7/redis/7.0/Dockerfile --tag ghcr.io/${{ github.actor }}/redis:7.0 && docker push ghcr.io/${{ github.actor }}/redis:7.0

      - name: Docker Buildx
        run: docker buildx create --name mybuilder --driver docker-container && docker buildx use mybuilder && docker run --privileged --rm tonistiigi/binfmt --install all 
    
      - name: Build the Nginx Docker image
        run: docker buildx build --platform linux/arm64,linux/arm/v7,linux/amd64 --file centos/centos7/redis/7.0/Dockerfile --tag ghcr.io/${{ github.actor }}/redis:7.0 . && docker push ghcr.io/${{ github.actor }}/redis:7.0
    
