name: Build Redis Docker Image Arm64

on:
  workflow_dispatch:

jobs:
  build-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Redis Docker image
        run: docker buildx build --platform=linux/arm64 --file centos/centos7/redis/7.0/Dockerfile --tag ghcr.io/${{ github.actor }}/redis:7.0-arm64 .

      - name: Push the Redis Docker image
        run: docker push ghcr.io/${{ github.actor }}/redis:7.0-arm64
