name: Docker Kafka Rocky Amd64

on:
  workflow_dispatch:

jobs:
  build-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Seatunnel Docker image
        run: docker build . --file rocky/9/kafka/3.5/Dockerfile --tag ghcr.io/${{ github.actor }}/kafka:3.5-rocky && docker push ghcr.io/${{ github.actor }}/kafka:3.5-rocky
