name: Docker Etcd Alpine Arm64

on:
  workflow_dispatch:

jobs:
  build-etcd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Build the Etcd Docker image Arm64
        run: docker buildx build --platform=linux/arm64 --file alpine/3.16/etcd/3.5/Dockerfile --tag ghcr.io/${{ github.actor }}/etcd:3.5-alpine-arm64 . --load

      - name: Push the Etcd Docker image Arm64
        run: docker push ghcr.io/${{ github.actor }}/etcd:3.5-alpine-arm64
