name: Build Mysql Docker Image

on:
  workflow_dispatch:

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Mysql Docker image
        run: docker build . --file centos/centos7/mysql/8.0/Dockerfile --tag ghcr.io/${{ github.actor }}/mysql:8.0 && docker push ghcr.io/${{ github.actor }}/mysql:8.0
    
