name: Docker PHP CentOS Arm64

on:
  workflow_dispatch:

jobs:
  build-php81:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the PHP 8.1 Docker image
        run: docker buildx build --platform=linux/arm64 --file centos/centos7/php/8.1/Dockerfile --tag ghcr.io/tikobus/php:8.1-arm64 . --load
 
      - name: Push the PHP 8.1 Docker image
        run: docker push ghcr.io/tikobus/php:8.1-arm64
