name: Build AmPHP Docker Image

on:
  workflow_dispatch:

jobs:
  build-amphp2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the AmPHP Docker image
        run: cd centos/centos7/amphp && docker build . --file Dockerfile --tag ghcr.io/tikobus/amphp:2.6 && docker push ghcr.io/tikobus/amphp:2.6
