name: Docker StableDiffusionWebui 1.5 Rocky Amd64

on:
  workflow_dispatch:

jobs:
  build-StableDiffusionWebui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the StableDiffusionWebui 8.1 Docker image
        run: docker build . --file rocky/9/stable-diffusion-webui/1.5/Dockerfile --tag ghcr.io/tikobus/stable-diffusion-webui:1.5-rocky && docker push ghcr.io/tikobus/stable-diffusion-webui:1.5-rocky
