name: Docker Filebeat Alpine Amd64

on:
  workflow_dispatch:

jobs:
  build-filebeat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Filebeat Docker image
        run: docker build --file alpine/3.16/filebeat/8.4/Dockerfile --tag ghcr.io/${{ github.actor }}/filebeat:8.4-alpine . 
    
      - name: Push the Filebeat Docker image
        run: docker push ghcr.io/${{ github.actor }}/filebeat:8.4-alpine
