name: Build Nginx Docker Image

on:
  workflow_dispatch:

jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build the Nginx Docker image
        run: docker buildx create --name mybuilder --driver docker-container && docker buildx build --push --platform linux/arm64,linux/arm/v7,linux/amd64 --file centos/centos7/nginx/Dockerfile --tag ghcr.io/${{ github.actor }}/nginx:1.22 . && docker push ghcr.io/${{ github.actor }}/nginx:1.22
    
